#服务的提供者1
---
server:
  port: 8781
  
spring:
  application:
    name: server-provider     #这个配置很重要
    
  profiles:  provider1

 
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/demo1
    username:  root
    password:  root
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/   #注册到服务注册中心
      
      
mybatis:
  mapper-locations:  classpath:mapper/*.xml
      
#服务的提供者2
---
server:
  port: 8782
  
spring:
  application:
    name: server-provider     #这个配置很重要，用于服务的提供者集群
  profiles:  provider2
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/   #注册到服务注册中心