server:
  port: 8763
  
spring:
  application:
    name: eureka-server
    
eureka:
  instance:
    hostname: peer3
    
  client:
    #registerWithEureka: false
    #fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/