server:
  port: 8002
  
spring:
  application:
    name: springboot-redis
    
    
  redis:
    host: localhost
    port: 6379
    timeout: 30
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
        max-wait: 20
   
    
