server:
  port: 8782
  
spring:
  application:
    name: server-provider     #这个配置很重要
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/demo1
    username:  root
    password:  root
  boot:
    admin:
      client:
        url:  http://localhost:8783

#配置consul，将该服务注册到consul上

  cloud:
   consul:
      host: localhost
      port: 8900
      discovery:
        service-name: service-producer      #注册到consul上的服务提供者名称
#eureka:
 # client:
  #  serviceUrl:
   #   defaultZone:  http://localhost:8761/eureka/   #注册到服务注册中心

management:
  endpoints:
    web:
      exposure:
        include: '*'  #监控所有的功能。
  endpoint:
    health:
      show-details: always
#  health:
#    redis:
#      enabled: false      #关闭redis服务健康检查
#    mongo:
#      enabled: false      #关闭MongoDB服务健康检查
#    solr:
#      enabled: false      #关闭solr服务健康检查
#    elasticsearch:
#      enabled: false      #关闭全局搜索服务健康检查      
      
mybatis:
  mapper-locations:  classpath:mapper/*.xml
      
