spring:
  profiles:
    active:
    - dev
    
logging:
  level:
    org.springframework.cloud.gateway: debug        #开启日志
  path: /Users/rose/mylog/gateway
  file: gateway-log
  config: classpath:logback-gateway.xml