server:
  port: 8761
  
spring:
  application:
    name: eureka-server
    
eureka:
  instance:
    hostname: localhost
    
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

      
      
