#服务注册中心1
---
server:
  port: 8761
  
spring:
  application:
    name: eureka-server
  profiles:  eurekaServer1
    
eureka:
  instance:
    hostname: peer1
    
    prefer-ip-address: true
  client:
   # registerWithEureka: false
    #fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer2:8762/eureka,http://peer3:8763/eureka/
      
#服务注册中心2
---
server:
  port: 8762
  
spring:
  application:
    name: eureka-server
  profiles:  eurekaServer2 
eureka:
  instance:
    hostname: peer2
    
  client:
    #registerWithEureka: false
    #fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/
      
#服务注册中心3
---
server:
  port: 8763
  
spring:
  application:
    name: eureka-server
  profiles:  eurekaServer3 
eureka:
  instance:
    hostname: peer3
    
  client:
    #registerWithEureka: false
    #fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
      
      
