server:
  port: 8768
  
spring:
  application:
    name: server-consumer
    
eureka:
  client:
    service-url:
      default-zone:  http://localhost:8761/eureka/
      
feign:
  hystrix:
    enabled: true 
    