server:
  port: 8768
  
spring:
  application:
    name: server-consumer
    
eureka:
  client:
    service-url:
      default-zone:  http://localhost:8761/eureka/
#开启hystrix服务熔断机制
feign:
  hystrix:
    enabled: true
    #开启feign熔断机制,如果默认值为false的话，@FeignClient(name = "server-provider", fallback = HelloSerciceHystrixImpl.class)中的fallback不会起作用

