server:
  port: 8783
  
spring:
  application:
    name: springboot-admin
  boot:
    admin:
      notify:
        mail:
          to:  jin2111843364@163.com,shuai.jin@mfashion.com.cn
          cc:  2111843364@qq.com
          from: jin2111843364@163.com
  mail:
    host: smtp.163.com
    username: jin2111843364@163.com
    password: abc123
    properties:
      mail.debug: false
      mail.smtp.auth: true   #安全认证(默认是true)
      mail.smtp.port: 465
      mail.smtp.ssl.enable: true  #开启ssl加密 否则项目启动时报530error
      mail.smtp.ssl.socketFactory: sf
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

          
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
      
      